---
- name: "[{{ service.name }}] Конфигурация секретов"
  vars:
    data: "{{ lookup('template', '{{ service.name }}/config.yml') }}"
    name: "{{ service.name }}"
  include_tasks: ../secret.yml

- name: "[{{ service.name }}] Выкладка сервиса"
  community.docker.docker_swarm_service:
    name: "{{ service.name }}"
    image: "{{ service.image }}"
    networks:
      - "{{ network_name }}"
    publish:
      - published_port: 9093
        target_port: 9093
    secrets:
      - secret_name: "{{ service.name }}"
        filename: /etc/alertmanager/alertmanager.yml
    placement:
      constraints:
        - node.role == manager
