---
- name: Leader
  hosts: leader
  roles:
    - role: preconfig
      tags: preconfig
    - role: swarm_init
      tags: swarm_init
    - role: set_labels
      tags: set_labels
    - role: registry_init
      tags: registry_init
    - role: build
      tags: build


- name: Managers
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    - role: swarm_join
      type: manager
      tags: swarm_join
    - role: set_labels
      tags: set_labels

- name: Workers
  hosts: workers
  roles:
    - role: preconfig
      tags: preconfig
    - role: swarm_join
      type: worker
      tags: swarm_join
