passwords:
  s1: string

env:
  wss_host: wss://domain.ru
  https_host: https://domain.ru
  domain: domain.ru

  grafana_https_host: https://grafana.domain.ru
  grafana_domain: grafana.domain.ru

  email_support: example@email.com
  email_report: example@email.com

  common_db:
    user: string
    password: string
    host: string
    port: 5432
    database: string
  movies_db:
    user: string
    password: string
    host: string
    port: 5432
    database: string
  api:
    access_token: string
    refresh_token: string
    smpt_pass: string
    smpt_user: string
    sentry_dsn: string
  app:
    captcha_key: string
    ym_account_id: 1234
    vibix_token: string
    collaps_token: string
    alloha_token: string
    veo_token: string
  bot:
    token: token
  health_bot:
    token: token
    message_thread_id: 9
    chat_id: "-1003588090545"
    admin: "@siparat"
  grafana:
    user: string
    password: string
