---
- name: "[{{ service.name }}] Создание директории данных"
  file:
    path: "{{ mount_folders.loki }}"
    state: directory
    mode: '0755'
    owner: "10001"
    group: "10001"

- name: "[{{ service.name }}] Конфигурация секретов"
  block:
    - vars:
        data: "{{ lookup('template', '{{ service.name }}/loki-config.yml.j2') }}"
        name: loki-config.yml
      include_tasks: ../secret.yml

- name: "[{{ service.name }}] Выкладка сервиса"
  community.docker.docker_swarm_service:
    name: "{{ service.name }}"
    image: "{{ service.image }}"
    networks:
      - "{{ network_name }}"
    user: "10001:10001"
    secrets:
      - secret_name: loki-config.yml
        filename: /etc/loki/local-config.yml
    mounts:
      - type: bind
        source: "{{ mount_folders.loki }}"
        target: /loki
    placement:
      constraints:
        - node.role == manager
