---
- name: "[{{ service.name }}] Конфигурация секретов"
  block:
    - vars:
        data: "{{ lookup('template', '{{ service.name }}/datasources.yml.j2') }}"
        name: datasources.yml
      include_tasks: ../secret.yml

- name: "[{{ service.name }}] Выкладка сервиса"
  community.docker.docker_swarm_service:
    name: "{{ service.name }}"
    image: "{{ service.image }}"
    force_update: true
    user: "472"
    secrets:
      - secret_name: datasources.yml
        filename: /etc/grafana/provisioning/datasources/datasources.yml
    mounts:
      - type: bind
        target: /var/lib/grafana
        source: "{{ mount_folders.grafana }}"
    placement:
      constraints:
        - node.labels.database == true
    networks:
      - "{{ network_name }}"
    publish:
      - target_port: 3000
        published_port: 3030
        mode: ingress
    env:
      GF_SECURITY_ADMIN_USER: "{{ env.grafana.user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ env.grafana.password }}"
      GF_SERVER_ROOT_URL: "{{ env.grafana_https_host }}"
      GF_SERVER_DOMAIN: "{{ env.grafana_domain }}"
