---
- name: "[{{ service.name }}] Конфигурация Prometheus"
  vars:
    data: "{{ lookup('template', '{{ service.name }}/prometheus.yml') }}"
    name: "{{ service.name }}_config"
  include_tasks: ../secret.yml

- name: "[{{ service.name }}] Конфигурация правил алертинга"
  vars:
    data: "{{ lookup('template', '{{ service.name }}/alert_rules.yml') }}"
    name: "{{ service.name }}_rules"
  include_tasks: ../secret.yml

- name: "[{{ service.name }}] Выкладка сервиса"
  community.docker.docker_swarm_service:
    name: "{{ service.name }}"
    image: "{{ service.image }}"
    networks:
      - "{{ network_name }}"
    publish:
      - published_port: 9090
        target_port: 9090
    secrets:
      - secret_name: "{{ service.name }}_config"
        filename: /etc/prometheus/prometheus.yml
      - secret_name: "{{ service.name }}_rules"
        filename: /etc/prometheus/alert_rules.yml
    placement:
      constraints:
        - node.role == manager
